In [25]:
import torch
from collections import deque
from copy import deepcopy

In [26]:
STATE_SIZE = 4
class StateHolder:
    def __init__(self, screen):
        self.frames = deque(maxlen = STATE_SIZE)
        for _ in range(STATE_SIZE):
            self.frames.append(screen)
        
    def reset(self):
        self.frames.clear()
    
    def push(self, frame):
        self.frames.append(frame)
        
    def get(self):
        # SLOW - !
        # frames = tuple(frame.type(torch.cuda.FloatTensor) for frame in self.frames)
        return torch.cat(tuple(self.frames), dim = 0).unsqueeze_(0)

In [27]:
a = StateHolder(0)
for i in range(10):
    a.push(torch.Tensor([i]))
a.get()

tensor([[6., 7., 8., 9.]])

In [28]:
b = StateHolder(0)
for i in range(10):
    b.push(torch.Tensor([i]))
c = deepcopy(b)
print(c.get())
print(b.get())

b.push(torch.Tensor([15]))

print(c.get())
print(b.get())

tensor([[6., 7., 8., 9.]])
tensor([[6., 7., 8., 9.]])
tensor([[6., 7., 8., 9.]])
tensor([[ 7.,  8.,  9., 15.]])
